# Generated by Django 2.2.5 on 2020-12-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeafoodApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seafood',
        ),
    ]
