# Generated by Django 2.2.5 on 2020-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeafoodApp', '0003_seafood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seafood',
            name='wild_caught',
            field=models.CharField(choices=[('Wild', 'Wild'), ('Farmed', 'Farmed')], max_length=15),
        ),
    ]
