# Generated by Django 2.2.5 on 2020-12-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('spirit', models.CharField(choices=[('vodka', 'vodka'), ('whiskey', 'whiskey'), ('tequila', 'tequila'), ('gin', 'gin'), ('rum', 'rum')], max_length=60)),
                ('ingredients', models.CharField(max_length=300)),
                ('flavor_profile', models.CharField(choices=[('sweet', 'sweet'), ('sour', 'sour'), ('spicy', 'spicy'), ('bitter', 'bitter'), ('boozy', 'boozy')], max_length=200)),
            ],
        ),
    ]
