# Generated by Django 2.2.5 on 2020-11-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindPetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablepet',
            name='description',
            field=models.CharField(help_text='Describe the wonderful animal here!', max_length=500),
        ),
    ]
