# Generated by Django 2.2.5 on 2020-11-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindPetApp', '0003_auto_20201127_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petapplicant',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='petapplicant',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
