# Generated by Django 2.2.5 on 2020-12-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindPetApp', '0004_auto_20201127_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petapplicant',
            old_name='email',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='petapplicant',
            old_name='location',
            new_name='state',
        ),
    ]
