# Generated by Django 2.2.5 on 2020-12-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='black_player',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player',
            field=models.CharField(max_length=120),
        ),
    ]
