# Generated by Django 2.2.5 on 2020-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0002_auto_20201202_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='end_time',
            field=models.DateField(),
        ),
    ]
