# Generated by Django 2.2.5 on 2020-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0004_auto_20201202_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgamegroup',
            name='game_list1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chessgamegroup',
            name='game_list2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
