# Generated by Django 2.2.5 on 2020-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0005_auto_20201202_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgamegroup',
            name='title',
            field=models.CharField(default='foo', max_length=120),
            preserve_default=False,
        ),
    ]
