# Generated by Django 2.2.5 on 2020-12-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0006_chessgamegroup_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgamegroup',
            name='game_list2',
        ),
        migrations.RemoveField(
            model_name='chessgamegroup',
            name='game_list1',
        ),
        migrations.AddField(
            model_name='chessgamegroup',
            name='game_list1',
            field=models.ManyToManyField(to='ChessApp.ChessGame'),
        ),
    ]
